# Generated by Django 4.2 on 2023-04-24 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.FloatField(null=True)),
                ('state', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('guestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_id', to=settings.AUTH_USER_MODEL)),
                ('hostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
